---
- name: Ensure cachefilesd is installed
  ansible.builtin.dnf:
    state: present
    name: cachefilesd
    install_weak_deps: false
  retries: 10
  delay: 1
  register: common_install_fs_cache
  until: common_install_fs_cache is successful
  when: not (common_ostree | bool)

- name: Ensure cachefilesd is installed
  community.general.rpm_ostree_pkg:
    state: present
    name: cachefilesd
  when: common_ostree | bool

- name: Ensure cachefilesd service is configured
  ansible.builtin.systemd_service:
    name: cachefilesd.service
    state: started
    enabled: true
    daemon_reload: true
