---
- name: Check if Grub default configuration was updated by RPM
  ansible.builtin.stat:
    path: /etc/default/grub.rpmnew
  register: common_grub_default_rpmnew

- name: Ensure latest Grub default configuration from RPM is used
  ansible.builtin.copy:
    remote_src: true
    src: /etc/default/grub.rpmnew
    dest: /etc/default/grub
    owner: root
    group: root
    mode: "0644"
  when: common_grub_default_rpmnew.stat.exists

- name: Ensure Grub options are configured
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    create: true
    state: "{{ (item.when | default(true)) | ternary('present', 'absent') }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - line: 'GRUB_TIMEOUT="{{ common_grub_timeout }}"'
      regexp: "^GRUB_TIMEOUT="
    - line: "GRUB_TIMEOUT_STYLE=hidden"
      regexp: "^GRUB_TIMEOUT_STYLE="
      when: "{{ common_grub_auto_hide | bool }}"
    - line: 'GRUB_HIDDEN_TIMEOUT="{{ common_grub_hidden_timeout }}"'
      regexp: "^GRUB_HIDDEN_TIMEOUT="
      when: "{{ common_grub_auto_hide | bool }}"
    - line: 'GRUB_HIDDEN_TIMEOUT_QUIET="true"'
      regexp: "^GRUB_HIDDEN_TIMEOUT_QUIET="
      when: "{{ common_grub_auto_hide | bool }}"
    - line: 'GRUB_CMDLINE_LINUX_DEFAULT="{{ common_grub_cmdline_linux_default | flatten | join(" ") }}"'
      regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
      when: "{{ (common_grub_cmdline_linux_default | flatten | length) > 0 and not (common_ostree | bool) }}"
    - line: "GRUB_DEFAULT=saved"
      regexp: "^GRUB_DEFAULT="
      when: "{{ common_grub_save_default | bool }}"
    - line: "GRUB_SAVEDEFAULT=true"
      regexp: "^GRUB_SAVEDEFAULT="
      when: "{{ common_grub_save_default | bool }}"

- name: Ensure Grub auto hide is configured
  ansible.builtin.command: "grub2-editenv - {{ common_grub_auto_hide | ternary('set menu_auto_hide=1', 'unset menu_auto_hide') }}"
  changed_when: false

- name: Ensure Grub Kernel options are configured
  ansible.builtin.command:
    "{{ ['rpm-ostree kargs --unchanged-exit-77', ['--append-if-missing='] | product(common_grub_cmdline_linux_default | flatten) | map('join', '')]
    | flatten | join(' ') }}"
  register: common_set_ostree_kernel_args
  changed_when: common_set_ostree_kernel_args.rc == 0
  failed_when: common_set_ostree_kernel_args.rc not in [ 0, 77 ]
  when: common_ostree | bool

- name: Ensure Ansible "python3-pexpect" requirement is installed
  ansible.builtin.dnf:
    state: present
    name: python3-pexpect
    install_weak_deps: false
  retries: 10
  delay: 1
  register: common_pg_python3_pexpect
  until: common_pg_python3_pexpect is successful
  when:
    - common_grub_password is defined
    - not (common_ostree | bool)

- name: Ensure Ansible "python3-pexpect" requirement is installed
  community.general.rpm_ostree_pkg:
    state: present
    name: python3-pexpect
  when:
    - common_grub_password is defined
    - common_ostree | bool

- name: Ensure Grub password is set
  when: common_grub_password is defined
  block:
    - name: Ensure Grub password is set
      ansible.builtin.expect:
        command: grub2-setpassword
        responses:
          ".*password": "{{ common_grub_password }}"
      changed_when: false
      no_log: true
  always:
    - name: Ensure Ansible "python3-pexpect" requirement is removed
      ansible.builtin.dnf:
        state: absent
        name: python3-pexpect
      when:
        - common_pg_python3_pexpect.changed # noqa no-handler
        - not (common_ostree | bool)

    - name: Ensure Ansible "python3-pexpect" requirement is removed
      community.general.rpm_ostree_pkg:
        state: absent
        name: python3-pexpect
      when:
        - common_pg_python3_pexpect.changed # noqa no-handler
        - common_ostree | bool

- name: Ensure Grub password is unset
  ansible.builtin.file:
    path: /boot/grub2/user.cfg
    state: absent
  when: common_grub_password is not defined

- name: Ensure Grub configuration is applied
  ansible.builtin.command: "grub2-mkconfig -o {{ item }}"
  changed_when: false
  loop:
    - /etc/grub2.cfg
    - /etc/grub2-efi.cfg

- name: Ensure Grub RPM package files metadata are in sync
  ansible.builtin.command: rpm --restore grub2-tools # noqa command-instead-of-module
  changed_when: false

- name: Ensure Grub "rpmnew" and "rpmsave" files are absent
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/default/grub.rpmnew
    - /etc/default/grub.rpmsave
