---
- name: Ensure Qemu guest agent is installed
  ansible.builtin.dnf:
    state: "{{ common_guest_qemu | bool | ternary('present', 'absent') }}"
    name: qemu-guest-agent
    install_weak_deps: false
  retries: 10
  delay: 1
  register: common_install_qemu_guest
  until: common_install_qemu_guest is successful
  when: not (common_ostree | bool)

- name: Ensure Qemu guest agent is installed
  community.general.rpm_ostree_pkg:
    state: "{{ common_guest_qemu | bool | ternary('present', 'absent') }}"
    name: qemu-guest-agent
  when: common_ostree | bool

- name: Ensure Incus guest agent is installed
  ansible.builtin.dnf:
    state: "{{ common_guest_incus | bool | ternary('present', 'absent') }}"
    name: incus-agent
    install_weak_deps: false
  retries: 10
  delay: 1
  register: common_install_incus_guest
  until: common_install_incus_guest is successful
  when: not (common_ostree | bool)

- name: Ensure Incus guest agent is installed
  community.general.rpm_ostree_pkg:
    state: "{{ common_guest_incus | bool | ternary('present', 'absent') }}"
    name: incus-agent
  when: common_ostree | bool
