---
- name: Ensure SMB client requirements are installed
  ansible.builtin.dnf:
    state: present
    name: cifs-utils
    install_weak_deps: false
  retries: 10
  delay: 1
  register: common_install_cifs_utils
  until: common_install_cifs_utils is successful
  when: not (common_ostree | bool)

- name: Ensure SMB client requirements are installed
  community.general.rpm_ostree_pkg:
    state: present
    name: cifs-utils
  when: common_ostree | bool

- name: Ensure SMB target mount directories are present
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ common_smb_mount }}"

- name: Mount SMB shares
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    opts: "{{ item.opts | default(omit) }}"
    fstype: cifs
    state: "{{ item.state | default('mounted') }}"
  loop: "{{ common_smb_mount }}"
